# -*- coding: utf-8 -*-
"""AAFT_std_inf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfZgEulQ21bs6Y5f4_UVRQShxVWRk0Nu
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Student Information Form")

# Text input for name
# User enters a single line of text
name = st.text_input("Enter your name")

# Number input for age
# User enters only numbers
age = st.number_input("Enter your age")

# Dropdown selection
# User selects one option
course = st.selectbox(
    "Select Course",
    ["BCA","BBA","MBA","MCA"]
)

# Radio button
# Select only one option
gender = st.radio(
    "Select Gender",
    ["Male","Female","Other"]
)


#multiselect
skills = st.multiselect(
    "Select your skills",
    ["Python", "Java", "C++", "AI", "Machine Learning"]
)
# Slider input
# User drags slider between values
marks = st.slider(
    "Enter Marks",
    0,100
)

# Checkbox
agree = st.checkbox(
    "I agree to terms"
)


# Button
if st.button("Submit"):

    st.write("Name:",name)
    st.write("Age:",age)
    st.write("Course:",course)
    st.write("Gender:",gender)
    st.write("Marks:",marks)
    st.write("Marks:",skills)

    if agree:
        st.success("Form Submitted")
    else:
        st.error("Please accept terms"
)