# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xp8S7mC39jkCDutzGGTHqzDxcGLMLEb4
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Streamlit library and give it a short name "st"
# %pip install streamlit
import streamlit as st


# Creates the main title on webpage
st.title("BMI Calculator")


# Creates a number input box for user weight
# Value entered is stored in variable "weight"
weight = st.number_input("Weight (kg)")


# Creates another number input for height
# Value entered is stored in variable "height"
height = st.number_input("Height (m)")


# Creates a button named "Calculate BMI"
# Code inside this block runs only after button click
if st.button("Calculate BMI"):


    # BMI Formula:
    # BMI = Weight / Height²
    # **2 means square of height
    bmi = weight / (height**2)


    # Display BMI result in a green success message
    # :.2f shows only 2 digits after decimal
    st.success(f"BMI: {bmi:.2f}")


    # If BMI is below 18.5
    # Show Underweight warning
    if bmi < 18.5:
        st.warning("Underweight")


    # If BMI is less than 25
    # Show Normal category
    elif bmi < 25:
        st.success("Normal")


    # If BMI is above or equal to 25
    # Show Overweight category
    else:
        st.error("Overweight")

