# -*- coding: utf-8 -*-
"""Online_Signing_Petition_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUTimmVSgbvoJbkhPujlniqWr0IKS-OB
"""

!pip install streamlit
import streamlit as st

st.title("Online Signing Petition")
st.error("Petition for the Resignation of Dharmendra Pradhan (Education Minister of India)")

# Input for
name_input = st.text_input("Enter Your Full Name:")

# Input for Signature
signature_input = st.text_input("Enter Your Digital Signature (Text):")

if st.button("Sign Petition"):
    if name_input.strip() == "" or signature_input.strip() == "":
        st.warning("Please fill out both fields before signing.")
    else:
        # Converting name to uppercase on submission
        uppercase_name = name_input.upper()

        st.success("Thank you for signing the petition!")
        st.info(f"**Name (Uppercase):** {uppercase_name}")
        st.info(f"**Signature:** {signature_input}")

