# -*- coding: utf-8 -*-
"""Student_Name_List_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dssvQ_GdgI_dEBmogfW_p1fGNpXOYr26
"""

!pip install streamlit
import streamlit as st

st.title("Class Student List Tracker")

if "student_list" not in st.session_state:
  st.session_state.student_list = []

# Input field for student name
new_student = st.text_input("Enter Student Name : ")
if st.button("Add Student to List"):
  if new_student.strip() != "":
    st.session_state.student_list.append(new_student.strip())
    st.success(f"'{new_student}' successfully added")

  else:
    st.warning("Please Enter a Valid Name")


# Displaying the current list of students
st.subheader("Current Student List")
if st.session_state.student_list:
  for index, name in enumerate(st.session_state.student_list, start = 1):
    st.write(f"{index}. {name}")
else:
  st.write("No names submitted yet")
