# -*- coding: utf-8 -*-
"""Table_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVrVTs_ZDkfnthdyYc-iFsjryzPV9iqP
"""

!pip install streamlit
import streamlit as st

st.title("Table Generator")
st.write("Enter a number to generate its mathematical table.")

num = st.number_input("Enter a Number", min_value=1, value=5, step=1)
if st.button("Generate Table"):
  st.subheader(f"Table of {num}")

  for i in range(1,11):
    st.write(f"**{num}** x **{i}** = **{num * i}**")
