# -*- coding: utf-8 -*-
"""TO_DO_List_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rRPSadILLwK3elDeL7aQnp648WlFIzq
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

# Creates main heading on webpage
st.title("To Do App")


# Check whether "tasks" list already exists
# in Streamlit session memory
if "tasks" not in st.session_state:

    # Create an empty list for storing tasks
    st.session_state.tasks=[]


# Create a text box to type task
# Store entered text inside variable task
task=st.text_input("Task")


# Create Add button
# Code runs only when button is clicked
if st.button("Add"):

    # Add entered task into task list
    st.session_state.tasks.append(task)


# Loop through every task in task list
for t in st.session_state.tasks:

    # Display task with check mark
    st.write("✅",t)

